const CONDITIONS = `
1/ Le site www.mavillepratique.fr n'entretient aucun lien avec une collectivité publique ou entreprise privée. 2/ Les prix sont établis pour un paiement comptant.
Les tarifs sont indiqués hors taxes. L'exécution d'une commande à un prix convenu n'emporte aucune obligation de la société France Media Communication au capital de 1000 euros, dont le siège social se situe au 9 rue de l'église,
93800 Epinay sur Seine, d'exécuter une commande ultérieure aux mêmes conditions. Le paiement de la première mise en ligne correspond à un acompte de la somme totale due précité dans les tarifs annuels HT. 3/ Préalablement à la mise en ligne, l'éditeur soumettra «une maquette de mise en ligne» a l'annonceur. Celle-ci sera adressée en priorité par courrier électronique à l'annonceur s'il indique une adresse e-mail sur le présent bon de commande, ou par courrier postal. En l'absence d'observation de l'annonceur notifiée dans un délai de 10 jours ouvrés à compter de la présentation de la «maquette de mise en ligne», cette dernière est réputée acceptée sans réserve. 4/ Les textes et clichés d'annonces doivent être remis à l'éditeur lors de la conclusion du bon de commande. En l'absence de communication de ces documents par l'annonceur dans un délai raisonnable, les indications mentionnées au bon de commande constitueront le message publicitaire. L'éditeur se réserve la faculté de refuser de mettre en ligne une annonce dont la nature, le texte et/ou la présentation seraient contraire aux intérêts du site www.mavillepratique.fr . L'éditeur ne saurait être responsable des textes à caractère publicitaire, lesquels sont mis en ligne sous la responsabilité exclusive de l'annonceur. 5/ Le délai de mise en ligne du message publicitaire est fixé à trente (30) jours ouvrés à compter de l'acceptation tacite ou expresse de la «maquette de mise en ligne» par l'annonceur, parvenue à l'éditeur. La société ne serait être tenue pour responsable de toute interruption de service ne relevant pas de sa responsabilité directe (panne électrique généralisée, panne des centres de routage, ou interruption des services de liaison entre le site et l'internaute, faits de guerre ou attentats,etc.) 6/ En revanche, l'erreur ou l'omission à l'occasion de la mise en ligne du message publicitaire ne pourra ouvrir droit au profit de l'annonceur, le cas échéant, qu'à une réduction du prix en fonction de l'importance du manquement. Les parties détermineront avec loyauté la réduction du prix dont il s'agit. 7/ En cas de résolution ou annulation du contrat pour le motif et dans les conditions précitées, l'éventuelle responsabilité de l'éditeur ne saurait en aucun cas excéder les sommes perçues au titre du présent contrat. 8/ Ledit contrat se renouvelle par tacite reconduction à chaque période anniversaire pour une durée totale maximale de 3 années. Le client bénéficie de la possibilité de résilier le contrat dans le delai d'un mois après l'envoi du dernier justificatif de parution, en notifiant ladite résiliation par tout moyen de communication pertinent conférant date certaine. 9/ La présente location est soumise au droit français et l'annonceur reconnaît que le présent contrat n'est pas soumis aux dispositions des articles L.
121- 23 à L. 121 -28 du Code de la consommation. En cas de litige de toute nature ou de contestation relative à la formation ou à l'exécution de la commande, le tribunal de commerce de Paris sera compétent. Cette compétence d'attribution s'applique également en cas de référé et/ou d'appel de garantie. La société France Media Communication est chargée de la mise en ligne, de la réalisation et de la prospection publicitaire. 10/ Le client annonceur déclare être titulaire des titres ou des diplômes et/ou autorisation qui lui permettent de figurer dans la rubrique choisie conformément à la réglementation qui lui est applicable.
*LA MISE EN LIGNE S'ENTEND D'UNE LOCATION D'UNE DURÉE D'UN MOIS.
L'annonceur reconnaît avoir pris connaissance de l'ensemble des présentes conditions générales de vente. La publicité paraît sous la responsabilité unique de l'annonceur qui certifie que la publicité est conforme à l'ensemble des lois et réglements en vigueur. L'annonceur garantit l'editeur contre tout recours qu'il pourrait encourir du fait des annonces publicitaires qu'il a fait paraître sur ordre.
`

export  {CONDITIONS};